import { PERMISSIONS, type PermissionCode } from './constants';

export const FILES_FEATURE_PERMISSIONS = [
  PERMISSIONS.VIEW_OWN_FILES,
  PERMISSIONS.VIEW_ALL_FILES,
  PERMISSIONS.VIEW_SHARED_FILES,
  PERMISSIONS.ACCESS_TEAM_FILES,
  PERMISSIONS.UPLOAD_OWN_FILES,
  PERMISSIONS.SHARE_FILES,
  PERMISSIONS.CREATE_FOLDER,
  PERMISSIONS.VIEW_FOLDERS,
  PERMISSIONS.UPDATE_FOLDERS,
  PERMISSIONS.DELETE_FOLDERS,
  PERMISSIONS.MANAGE_FOLDERS,
] as const satisfies readonly PermissionCode[];

export const MEETINGS_FEATURE_PERMISSIONS = [
  PERMISSIONS.VIEW_MEETINGS,
  PERMISSIONS.JOIN_MEETING,
  PERMISSIONS.PLAN_MEETINGS,
  PERMISSIONS.USE_VIDEOCONFERENCE,
] as const satisfies readonly PermissionCode[];

export const CALENDAR_FEATURE_PERMISSIONS = [
  PERMISSIONS.VIEW_CALENDAR,
  PERMISSIONS.USE_CALENDAR_PLANNING,
] as const satisfies readonly PermissionCode[];

export const TEAMS_FEATURE_PERMISSIONS = [
  PERMISSIONS.VIEW_TEAMS,
] as const satisfies readonly PermissionCode[];

export const MY_TEAMS_VIEW_PERMISSIONS = [
  PERMISSIONS.VIEW_MY_TEAMS,
] as const satisfies readonly PermissionCode[];

export const USERS_VIEW_PERMISSIONS = [
  PERMISSIONS.VIEW_ALL_USERS,
  PERMISSIONS.MANAGE_ACCOUNTS,
] as const satisfies readonly PermissionCode[];

export const USERS_INVITE_PERMISSIONS = [
  PERMISSIONS.INVITE_COLLABORATORS,
  PERMISSIONS.CREATE_USERS,
  PERMISSIONS.MANAGE_ACCOUNTS,
] as const satisfies readonly PermissionCode[];

export const USERS_FEATURE_PERMISSIONS = [
  ...USERS_VIEW_PERMISSIONS,
  ...USERS_INVITE_PERMISSIONS,
] as const satisfies readonly PermissionCode[];

export const NOTES_FEATURE_PERMISSIONS = [
  PERMISSIONS.VIEW_NOTES,
  PERMISSIONS.CREATE_NOTES,
  PERMISSIONS.UPDATE_NOTES,
  PERMISSIONS.SHARE_NOTES,
] as const satisfies readonly PermissionCode[];

/** Accès nav / routes Polls : visible pour tout rôle ayant polls.view (collaborateur inclus). */
export const POLLS_FEATURE_PERMISSIONS = [
  PERMISSIONS.VIEW_POLLS,
] as const satisfies readonly PermissionCode[];

export const POLLS_CREATE_PERMISSIONS = [
  PERMISSIONS.CREATE_POLLS,
] as const satisfies readonly PermissionCode[];

export const SETTINGS_FEATURE_PERMISSIONS = [
  PERMISSIONS.VIEW_SETTINGS,
  PERMISSIONS.UPDATE_SETTINGS,
  PERMISSIONS.MANAGE_SETTINGS,
  PERMISSIONS.VIEW_TEAM_SETTINGS,
  PERMISSIONS.UPDATE_TEAM_SETTINGS,
  PERMISSIONS.VIEW_COMPANY_SETTINGS,
  PERMISSIONS.UPDATE_COMPANY_SETTINGS,
  PERMISSIONS.VIEW_SECURITY_SETTINGS,
  PERMISSIONS.UPDATE_SECURITY_SETTINGS,
  PERMISSIONS.VIEW_BILLING_SETTINGS,
  PERMISSIONS.UPDATE_BILLING_SETTINGS,
  PERMISSIONS.VIEW_PROFILE_SETTINGS,
  PERMISSIONS.UPDATE_PROFILE_SETTINGS,
  PERMISSIONS.VIEW_PREFERENCES_SETTINGS,
  PERMISSIONS.UPDATE_PREFERENCES_SETTINGS,
  PERMISSIONS.VIEW_TEAM_MEMBERS_SETTINGS,
  PERMISSIONS.UPDATE_TEAM_MEMBERS_SETTINGS,
  PERMISSIONS.VIEW_ROLES_SETTINGS,
  PERMISSIONS.UPDATE_ROLES_SETTINGS,
  PERMISSIONS.VIEW_INVITATIONS_SETTINGS,
  PERMISSIONS.UPDATE_INVITATIONS_SETTINGS,
  PERMISSIONS.VIEW_GENERAL_SETTINGS,
  PERMISSIONS.UPDATE_GENERAL_SETTINGS,
  PERMISSIONS.VIEW_DASHBOARD_SETTINGS,
  PERMISSIONS.UPDATE_DASHBOARD_SETTINGS,
  PERMISSIONS.VIEW_DEFAULTS_SETTINGS,
  PERMISSIONS.UPDATE_DEFAULTS_SETTINGS,
  PERMISSIONS.VIEW_BRAND_SETTINGS,
  PERMISSIONS.UPDATE_BRAND_SETTINGS,
  PERMISSIONS.VIEW_EMAIL_ACCOUNTS_SETTINGS,
  PERMISSIONS.UPDATE_EMAIL_ACCOUNTS_SETTINGS,
  PERMISSIONS.VIEW_EMAIL_TEMPLATES_SETTINGS,
  PERMISSIONS.UPDATE_EMAIL_TEMPLATES_SETTINGS,
  PERMISSIONS.VIEW_ASSIGNMENT_RULES_SETTINGS,
  PERMISSIONS.UPDATE_ASSIGNMENT_RULES_SETTINGS,
  PERMISSIONS.VIEW_OWN_ROLE_PERMISSIONS,
  PERMISSIONS.MANAGE_ROLES_PERMISSIONS,
  PERMISSIONS.EDIT_OWN_ACCOUNT,
] as const satisfies readonly PermissionCode[];

export const ADMIN_FEATURE_PERMISSIONS = [
  PERMISSIONS.MANAGE_ROLES_PERMISSIONS,
  PERMISSIONS.MANAGE_SETTINGS,
  PERMISSIONS.CONFIGURE_PLATFORM,
  PERMISSIONS.MANAGE_ACCOUNTS,
  PERMISSIONS.VIEW_AUDIT_LOGS,
] as const satisfies readonly PermissionCode[];

export const TEAM_CREATE_PERMISSIONS = [
  PERMISSIONS.CREATE_TEAM,
  PERMISSIONS.MANAGE_TEAM,
] as const satisfies readonly PermissionCode[];

export const TEAM_DELETE_PERMISSIONS = [
  PERMISSIONS.DELETE_TEAM,
  PERMISSIONS.MANAGE_TEAM,
] as const satisfies readonly PermissionCode[];

export const FEATURE_PERMISSION_REQUIREMENTS = {
  calendar: CALENDAR_FEATURE_PERMISSIONS,
  chat: [PERMISSIONS.CHAT_WITH_COLLABORATORS],
  dashboard: [PERMISSIONS.VIEW_DASHBOARD],
  files: FILES_FEATURE_PERMISSIONS,
  meetings: MEETINGS_FEATURE_PERMISSIONS,
  myTeams: MY_TEAMS_VIEW_PERMISSIONS,
  notes: NOTES_FEATURE_PERMISSIONS,
  notifications: [PERMISSIONS.VIEW_NOTIFICATIONS],
  polls: POLLS_FEATURE_PERMISSIONS,
  settings: SETTINGS_FEATURE_PERMISSIONS,
  teams: TEAMS_FEATURE_PERMISSIONS,
  users: USERS_FEATURE_PERMISSIONS,
} as const satisfies Record<string, readonly PermissionCode[]>;
