import { PERMISSIONS, type PermissionCode } from './constants';

export const FILES_FEATURE_PERMISSIONS = [
  PERMISSIONS.VIEW_OWN_FILES,
  PERMISSIONS.VIEW_ALL_FILES,
  PERMISSIONS.VIEW_SHARED_FILES,
  PERMISSIONS.ACCESS_TEAM_FILES,
  PERMISSIONS.UPLOAD_OWN_FILES,
  PERMISSIONS.SHARE_FILES,
] as const satisfies readonly PermissionCode[];

export const MEETINGS_FEATURE_PERMISSIONS = [
  PERMISSIONS.VIEW_MEETINGS,
  PERMISSIONS.JOIN_MEETING,
  PERMISSIONS.PLAN_MEETINGS,
  PERMISSIONS.USE_VIDEOCONFERENCE,
] as const satisfies readonly PermissionCode[];

export const CALENDAR_FEATURE_PERMISSIONS = [
  PERMISSIONS.VIEW_CALENDAR,
  PERMISSIONS.USE_CALENDAR_PLANNING,
] as const satisfies readonly PermissionCode[];

export const TEAMS_FEATURE_PERMISSIONS = [
  PERMISSIONS.VIEW_TEAMS,
  PERMISSIONS.JOIN_TEAM,
  PERMISSIONS.CREATE_TEAM,
  PERMISSIONS.MANAGE_TEAM,
] as const satisfies readonly PermissionCode[];

export const USERS_VIEW_PERMISSIONS = [
  PERMISSIONS.VIEW_ALL_USERS,
  PERMISSIONS.MANAGE_ACCOUNTS,
] as const satisfies readonly PermissionCode[];

export const USERS_INVITE_PERMISSIONS = [
  PERMISSIONS.INVITE_COLLABORATORS,
  PERMISSIONS.CREATE_USERS,
  PERMISSIONS.MANAGE_ACCOUNTS,
] as const satisfies readonly PermissionCode[];

export const USERS_FEATURE_PERMISSIONS = [
  ...USERS_VIEW_PERMISSIONS,
  ...USERS_INVITE_PERMISSIONS,
] as const satisfies readonly PermissionCode[];

export const NOTES_FEATURE_PERMISSIONS = [
  PERMISSIONS.VIEW_NOTES,
  PERMISSIONS.CREATE_NOTES,
  PERMISSIONS.UPDATE_NOTES,
  PERMISSIONS.SHARE_NOTES,
] as const satisfies readonly PermissionCode[];

export const SETTINGS_FEATURE_PERMISSIONS = [
  PERMISSIONS.VIEW_SETTINGS,
  PERMISSIONS.MANAGE_SETTINGS,
  PERMISSIONS.VIEW_COMPANY_SETTINGS,
  PERMISSIONS.VIEW_SECURITY_SETTINGS,
  PERMISSIONS.VIEW_BILLING_SETTINGS,
  PERMISSIONS.VIEW_OWN_ROLE_PERMISSIONS,
  PERMISSIONS.MANAGE_ROLES_PERMISSIONS,
  PERMISSIONS.EDIT_OWN_ACCOUNT,
] as const satisfies readonly PermissionCode[];

export const ADMIN_FEATURE_PERMISSIONS = [
  PERMISSIONS.MANAGE_ROLES_PERMISSIONS,
  PERMISSIONS.MANAGE_SETTINGS,
  PERMISSIONS.CONFIGURE_PLATFORM,
  PERMISSIONS.MANAGE_ACCOUNTS,
] as const satisfies readonly PermissionCode[];

export const TEAM_CREATE_PERMISSIONS = [
  PERMISSIONS.CREATE_TEAM,
  PERMISSIONS.MANAGE_TEAM,
] as const satisfies readonly PermissionCode[];

export const FEATURE_PERMISSION_REQUIREMENTS = {
  calendar: CALENDAR_FEATURE_PERMISSIONS,
  chat: [PERMISSIONS.CHAT_WITH_COLLABORATORS],
  dashboard: [PERMISSIONS.VIEW_DASHBOARD],
  files: FILES_FEATURE_PERMISSIONS,
  meetings: MEETINGS_FEATURE_PERMISSIONS,
  notes: NOTES_FEATURE_PERMISSIONS,
  notifications: [PERMISSIONS.VIEW_NOTIFICATIONS],
  settings: SETTINGS_FEATURE_PERMISSIONS,
  teams: TEAMS_FEATURE_PERMISSIONS,
  users: USERS_FEATURE_PERMISSIONS,
} as const satisfies Record<string, readonly PermissionCode[]>;
