import type { MailFolder, MailMessage } from "./types";

export const MAIL_ACCOUNT = {
  name: "Yann Hallage",
  email: "yann@acredispace.com",
  avatarInitials: "YH",
};

export const MAIL_FOLDERS: MailFolder[] = [
  { id: "inbox", label: "Inbox", count: 528, icon: "inbox" },
  { id: "starred", label: "Starred", icon: "star" },
  { id: "snoozed", label: "Snoozed", icon: "snooze" },
  { id: "sent", label: "Sent", icon: "sent" },
  { id: "drafts", label: "Drafts", count: 3, icon: "drafts" },
  { id: "purchases", label: "Purchases", icon: "purchases" },
  { id: "more", label: "More", icon: "more" },
];

export const MAIL_LABELS: MailFolder[] = [
  { id: "contabo", label: "contabo", icon: "label" },
];

export const MOCK_MESSAGES: MailMessage[] = [
  {
    id: "1",
    sender: "Praveen Kumar",
    subject: "[rtCamp/training-calendar] Pull request opened: #122 Fix...",
    snippet:
      "opened a new pull request for rtCamp/training-calendar: #122 Fix calendar sync",
    date: "3:19 PM",
    unread: true,
    starred: false,
    important: true,
    category: "primary",
    folder: "inbox",
    hoverPills: ["View Pull Request", "Unsubscribe"],
  },
  {
    id: "2",
    sender: "Ayush",
    subject: "[rtCamp/training-calendar] Run failed: CI / build...",
    snippet: "CI workflow failed on branch feat/calendar-sync — view logs",
    date: "2:54 PM",
    unread: true,
    starred: false,
    important: true,
    category: "primary",
    folder: "inbox",
    hoverPills: ["View workflow run"],
  },
  {
    id: "3",
    sender: "Cloudflare",
    subject: "[Cloudflare] Privacy Policy Update",
    snippet:
      "We've updated our Privacy Policy. Please review the changes that take effect soon.",
    date: "1:12 PM",
    unread: false,
    starred: false,
    important: false,
    category: "primary",
    folder: "inbox",
  },
  {
    id: "4",
    sender: "yannhallage",
    subject: "[acredispace/api] Run failed at startup",
    snippet: "Job failed: Application failed to start — NullPointerException in...",
    date: "12:41 PM",
    unread: true,
    starred: false,
    important: true,
    category: "primary",
    folder: "inbox",
    hoverPills: ["View workflow run"],
  },
  {
    id: "5",
    sender: "Lovable",
    subject: "Your Lovable project is ready",
    snippet: "We finished generating your app preview. Open the project to continue editing.",
    date: "11:05 AM",
    unread: false,
    starred: true,
    important: false,
    category: "primary",
    folder: "inbox",
  },
  {
    id: "6",
    sender: "DigitalOcean",
    subject: "Your Droplet usage report for July",
    snippet:
      "Here's a summary of resource usage across your DigitalOcean account this month.",
    date: "10:22 AM",
    unread: true,
    starred: false,
    important: true,
    category: "primary",
    folder: "inbox",
  },
  {
    id: "7",
    sender: "The Render team",
    subject: "Deploy succeeded — acredispace-api",
    snippet: "Your service acredispace-api was successfully deployed to Oregon.",
    date: "9:48 AM",
    unread: false,
    starred: false,
    important: false,
    category: "primary",
    folder: "inbox",
  },
  {
    id: "8",
    sender: "GitHub",
    subject: "[acredispace/client] 3 new comments on pull request #84",
    snippet: "review requested changes on feat/mail-page — see conversation",
    date: "Aug 5",
    unread: true,
    starred: false,
    important: true,
    category: "primary",
    folder: "inbox",
    hoverPills: ["View Pull Request"],
  },
  {
    id: "9",
    sender: "Vercel",
    subject: "Deployment Ready — acredi-space-client",
    snippet: "Your production deployment completed successfully. Visit the preview URL.",
    date: "Aug 5",
    unread: false,
    starred: false,
    important: false,
    category: "primary",
    folder: "inbox",
  },
  {
    id: "10",
    sender: "Notion Team",
    subject: "Weekly digest: 12 updates in Acredi Space",
    snippet: "Catch up on pages edited by your teammates this week.",
    date: "Aug 4",
    unread: false,
    starred: false,
    important: false,
    category: "primary",
    folder: "inbox",
  },
  {
    id: "11",
    sender: "Stripe",
    subject: "Payment of $49.00 was successful",
    snippet: "Your payment to Acredi Space Pro was processed. Receipt attached.",
    date: "Aug 4",
    unread: false,
    starred: false,
    important: true,
    category: "primary",
    folder: "inbox",
  },
  {
    id: "12",
    sender: "Figma",
    subject: "You were invited to Design System — Acredi",
    snippet: "Open the file to start collaborating with your team.",
    date: "Aug 3",
    unread: true,
    starred: false,
    important: false,
    category: "primary",
    folder: "inbox",
  },
  {
    id: "13",
    sender: "Vanessa de Jumia",
    subject: "Flash sale — up to 70% off electronics",
    snippet: "Don't miss today's deals on phones, laptops and more.",
    date: "Aug 6",
    unread: true,
    starred: false,
    important: false,
    category: "promotions",
    folder: "inbox",
  },
  {
    id: "14",
    sender: "LinkedIn",
    subject: "You appeared in 8 searches this week",
    snippet: "See who viewed your profile and grow your network.",
    date: "Aug 5",
    unread: true,
    starred: false,
    important: false,
    category: "social",
    folder: "inbox",
  },
  {
    id: "15",
    sender: "Draft — Me",
    subject: "Follow-up on the Q3 roadmap",
    snippet: "(No content)",
    date: "Aug 2",
    unread: false,
    starred: false,
    important: false,
    category: "primary",
    folder: "drafts",
  },
];

export const PROMOTIONS_TAB_PREVIEW = "Vanessa de Jumia...";
export const MAIL_PAGINATION = { from: 1, to: 50, total: 1105 };
